language: node_js
node_js: 
  - "lts/*"
cache:
  directories:
    - "node_modules"
services:
  - postgresql
 before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - npm run test
after_script: ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success: 
  - npm run cover
